In [38]:
import pandas as pd 
import numpy as np

In [39]:
data = pd.read_csv(r'C:\Users\sunil\Downloads\Machine_Learnig\Datasets\train.csv')
print(data)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [41]:
data.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [46]:
data

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data.drop(columns="Survived"),data['Survived'],test_size=0.2)

In [51]:
X_train

     Pclass     Sex    Age  SibSp  Parch      Fare Embarked
145       2    male  19.00      1      1   36.7500        S
78        2    male   0.83      0      2   29.0000        S
679       1    male  36.00      0      1  512.3292        C
301       3    male    NaN      2      0   23.2500        Q
48        3    male    NaN      2      0   21.6792        C
..      ...     ...    ...    ...    ...       ...      ...
721       3    male  17.00      1      0    7.0542        S
472       2  female  33.00      1      2   27.7500        S
153       3    male  40.50      0      2   14.5000        S
448       3  female   5.00      2      1   19.2583        C
11        1  female  58.00      0      0   26.5500        S

[712 rows x 7 columns]

In [57]:
print(y_train)

145    0
78     1
679    1
301    1
48     0
      ..
721    0
472    1
153    0
448    1
11     1
Name: Survived, Length: 712, dtype: int64

In [66]:
data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [77]:
from sklearn.impute import SimpleImputer

age_si = SimpleImputer()
embarked_si = SimpleImputer(strategy='most_frequent')

x_train_age_si = age_si.fit_transform(X_train[['Age']])
x_test_age_si = age_si.fit_transform(X_test[['Age']])

x_train_embarked_si = embarked_si.fit_transform(X_train[['Embarked']])
x_test_embarked_si = embarked_si.fit_transform(X_test[['Embarked']])

In [78]:
x_test_age_si.shape
x_train_age_si.shape

(712, 1)

In [80]:
x_train_embarked_si.shape

(712, 1)

In [82]:
from sklearn.preprocessing import OneHotEncoder

ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(x_train_embarked_si)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(x_test_embarked_si)

In [83]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], shape=(712, 2))

In [84]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]], shape=(712, 3))

In [87]:
X_train.head()

     Pclass   Sex    Age  SibSp  Parch      Fare Embarked
145       2  male  19.00      1      1   36.7500        S
78        2  male   0.83      0      2   29.0000        S
679       1  male  36.00      0      1  512.3292        C
301       3  male    NaN      2      0   23.2500        Q
48        3  male    NaN      2      0   21.6792        C

In [88]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [90]:
X_train_transformed = np.concatenate((X_train_rem,x_train_age_si,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,x_test_age_si,X_test_sex,X_test_embarked),axis=1)

In [91]:
X_train_transformed

array([[2., 1., 1., ..., 0., 0., 1.],
       [2., 0., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 1., 0., 0.],
       ...,
       [3., 0., 2., ..., 0., 0., 1.],
       [3., 2., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(712, 10))

In [93]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [95]:
y_pred = dtc.predict(X_test_transformed)
y_pred

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1])

In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7877094972067039